language: java
sudo: false
jdk:
- oraclejdk7
install: true
script: "./buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/dists/gradle-2.10-bin"
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_1de8ede716d0_key -iv $encrypted_1de8ede716d0_iv -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- ./gradlew jacocoTestReport coveralls
